### ISSUE TITLE
Data Pipeline using Kubernetes and Argo

### ISSUE THREAD

**Issue by mayankpande88** [mayankpande88/my-learnings#2]
### What is Argo ?
 Argo is Kubernetes CRD which allows you to run pipelines natively on your cluster. It allows to create directed acyclic graph of “steps” and execute them in serial or in parallel. It also provides UI for monitoring and to run workflows.
Argo adds a new object to Kubernetes called a Workflow, using this workflow object we can provide different steps.

Some of Argo’s features include:
- Conditional execution
- Artifacts 
- Timeouts and retry logic
- Recursion and flow control
- Suspend, resume, and cancellation

### Installing Argo

```
kubectl create namespace argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/install.yaml
```

### Example for Workflow

Lets create and workflow where task generate-parameter creates some data and task consume-parameter consumes parameter generated from generate-parameter task.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: my-argo-wf
spec:
  entrypoint: output-parameter
  templates:
  - name: output-parameter
    steps:
    - - name: generate-parameter
        template: producer
    - - name: consume-parameter
        template: consumer
        arguments:
          parameters:
          - name: message
            value: "{{steps.generate-parameter.outputs.parameters.hello-param}}"

  - name: producer
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["sleep 1; echo -n hello world > /tmp/hello_world.txt"]
    outputs:
      parameters:
      - name: hello-param
        valueFrom:
          default: "Foobar"
          path: /tmp/hello_world.txt

  - name: consumer
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{inputs.parameters.message}}"]
```

We can submit argo workflow using `kubectl` 
`kubectl apply -f my-argo-wf.yaml`

Or we can use [Argo CLI](https://github.com/argoproj/argo/releases) as well

`argo submit my-argo-wf.yaml`

Finally this is how it looks on argo UI
![Screenshot (159)](https://user-images.githubusercontent.com/32476957/88687574-1335cc80-d116-11ea-9978-e521114258f6.png)

![Screenshot (160)](https://user-images.githubusercontent.com/32476957/88687710-38c2d600-d116-11ea-92b2-cdfedc6d21af.png)
